Dawn update
wgslsmith/wgslsmith pull request #27
Opened 2024-01-03 11:10 UTC by ambergorzynski

Updates build and program generation to be compatible with a more recent version of Dawn (commit [f5d6487f00](https://dawn.googlesource.com/dawn/+/f5d6487f00dd64af4ef0bd846b578282296ef3c3)). Also adds a build option to specify a particular Dawn version via a filepath to a folder containing Dawn.

2024-01-03 20:34 UTC, hasali19 commented
Thanks for the PR! Please could you bump the submodule in `external/dawn` to whichever dawn commit you've tested this with.

2024-01-03 21:13 UTC, hasali19 requested changes
Good stuff! Added a few mostly style related comments.

2024-01-03 21:13 UTC, hasali19 commented on .cargo/config.toml
This path looks system specific. Could you remove this file please.

2024-01-03 21:13 UTC, hasali19 commented on build.py
> +    parser.add_argument("-dawn_path", default="external/dawn")
For stylistic consistency:
```suggestion
    parser.add_argument("--dawn-path", default="external/dawn")
```

2024-01-03 21:13 UTC, hasali19 commented on crates/ast/src/writer.rs
> -                    if self.options.concise_stage_attrs {
If the `concise_stage_attrs` option is no longer required, could you remove it please.

2024-01-03 21:13 UTC, hasali19 commented on crates/dawn/build.rs
> +        .unwrap()
```suggestion
    let common_libs = fs::read_dir(dawn_lib_dir)?
```
https://rustjobs.dev/blog/the-question-mark-operator-in-rust/

2024-01-03 21:13 UTC, hasali19 commented on crates/dawn/build.rs
> +        let lib_name = &lib_name[3..];
Does this work on all platforms? Conventionally libraries on unix systems are prefixed with "lib", but not on Windows. Has Dawn changed its changed its naming?

2024-01-03 21:13 UTC, hasali19 commented on crates/dawn/build.rs
> +        println!("cargo:rustc-link-lib=static={}", lib_name);
```suggestion
        println!("cargo:rustc-link-lib=static={lib_name}");
```
Simple variables can go directly inside the braces, which is a bit neater.

2024-01-03 21:13 UTC, hasali19 commented on crates/dawn/src/lib.cpp
> +       which was in turn deprecated. TODO: check replacement code */
Does this TODO still need to be addressed? If not, remove it.

2024-01-03 21:13 UTC, hasali19 commented on crates/dawn/src/lib.cpp
> +    //instance->DiscoverDefaultAdapters();
Any reason to keep the commented code?

2024-01-03 21:13 UTC, hasali19 commented on crates/tint/build.rs
> +        .unwrap()
```suggestion
    let libs = fs::read_dir(dawn_lib_dir)?
```

2024-01-03 21:13 UTC, hasali19 commented on crates/tint/build.rs
> +        let lib_name = &lib_name[3..];
Same comment about platform compatibility.

2024-01-03 21:13 UTC, hasali19 commented on crates/tint/src/lib.cpp
> +    //auto transformed = transform_manager.Run(program.get(), std::move(transform_inputs));
Any reason to keep the commented code?

2024-01-03 23:52 UTC, hasali19 commented
Took the liberty of merging in some changes from `main` to enable the Actions workflow to run.

2024-01-04 12:49 UTC, ambergorzynski commented on .cargo/config.toml
I thought this config file was necessary to pass the Dawn path but in fact it is not! Removed.

2024-01-04 13:10 UTC, ambergorzynski commented on crates/ast/src/writer.rs
> -                    if self.options.concise_stage_attrs {
Removed throughout

2024-01-04 14:30 UTC, ambergorzynski commented on crates/dawn/build.rs
> +        let lib_name = &lib_name[3..];
Oops! No - removing the target-based naming was just a mistake. I have reinstated the previous target-based lib name. I have not tested it on a windows machine though.

2024-01-04 14:48 UTC, ambergorzynski commented on crates/tint/build.rs
> +        let lib_name = &lib_name[3..];
Changed as for the other case

2024-01-04 22:17 UTC, hasali19 commented
> Took the liberty of merging in some changes from `main` to enable the Actions workflow to run. Once you've updated the submodule, I'll mirror the change at https://github.com/wgslsmith/dawn-build, which will enable that version to be used in the workflow.

@ambergorzynski I've published a new dawn build. Could you update the version in `.github/dependency_versions.yaml` to `autobuild-2024-01-04-21-29`, which should enable the build and tests to pass. The checks are also failing [here](https://github.com/wgslsmith/wgslsmith/actions/runs/7411040004/job/20164661678?pr=27) due to some formatting issues I think, can you fix it please.

2024-01-05 11:35 UTC, ambergorzynski commented
MacOS test is failing due to an undefined symbol "___isPlatformVersionAtLeast" in the Dawn source code. This looks like an issue with Xcode versions (e.g. see [here](https://forums.developer.apple.com/forums/thread/123003)). I can try specifying the Xcode version in ci.yml (although it looks like the default version in macos-latest should be sufficiently high) - does that sound OK or do you have other suggestions?

2024-01-05 13:26 UTC, hasali19 commented
Hmm, could also be an issue with how I'm building dawn for macos. Rather painful to debug since I don't actually have a mac. Give it a go, and if it doesn't work I'm happy to just disable the macos build and merge (assuming you don't need macos support).

2024-01-05 14:27 UTC, ambergorzynski commented
OK, I'll try a few things and then give up if it's too tricky. I do have a mac, but I'm mainly using a Linux machine so no problem if we can't figure out mac support for now.

2024-01-09 16:48 UTC, ambergorzynski commented
I tried building on my Mac and it also fails there, although with a slightly different error (cannot locate tint/dawn header files). I can spend some more time separately debugging this to figure out what the issues is, although I may not be super speedy.

2024-01-09 21:56 UTC, hasali19 commented
Sure, no problem. In the meantime do you think this is good to merge now if I disable the macos build?

2024-01-10 08:56 UTC, ambergorzynski commented
Yes I think it's good to merge without the macOS build, thanks!

2024-01-12 22:41 UTC, hasali19 approved these changes

2024-01-12 22:43 UTC, merged